### ISSUE TITLE
[Question]only Levels-To-Token？

### ISSUE THREAD

**Issue by MintSkye** [TheCoolestPaul/Tokens#10]
in the config I only see the "Levels-To-Token" belong to mcmmo,which mean use mcmmo level to redeem the tokens?
I dont know what the meaning is. So i changed the setting number from 1 to 3 but when i use token to redeem the mcmmo level , finding that one token only redeem one mcmmo level and i couldnt find any way to use mcmmo level to redeem token.
Hope developer could add a funtion to let tokens to redeem custom level ,thx :)
sorry for my bad english.

**Comment by TheCoolestPaul** [comment]
It seems that whatever number is it is currently useless. I'll work on a fix real quick.

**Comment by TheCoolestPaul** [comment]
How the function is supposed to work, is that you can redeem a token for a mcmmo level in a skill, and the config.yml sets how many levels 1 token is worth.

**Comment by TheCoolestPaul** [comment]
Fixed will release 3.4.5
