### ISSUE TITLE
Add BossShopPro Support

### ISSUE THREAD

**Issue by FunkyNico** [TheCoolestPaul/Tokens#14]
Add support for BossShopPro so you can use tokens as points on a store or gui's that needs tokens.

**Comment by TheCoolestPaul** [comment]
I will definitely look into adding support for this plugin, thank you for the suggestion

**Comment by TheCoolestPaul** [comment]
Just to update the issue, I've added BSP BETA support [here](https://github.com/TheCoolestPaul/Tokens/releases/tag/3.9.7-BETA-BSP), if anyone has any bugs with it, you can mark it in this issue.
