### ISSUE TITLE
Unsupported API version 1.15

### ISSUE THREAD

**Issue by Eik0** [TheCoolestPaul/Tokens#38]
**Describe the bug**
The plugin won't load on my 1.14.4 Paper server. I get the error "Unsupported API version 1.15"

**Plugin version:** 3.8.1

**Error message**
https://hastebin.com/yafukufema.sql

**Comment by TheCoolestPaul** [comment]
I'll be sure to add it right quick

**Comment by TheCoolestPaul** [comment]
Fixed by 3.8.2 release!
