### ISSUE TITLE
Cannot start server - Startup error

### ISSUE THREAD

**Issue by teszeo** [TheCoolestPaul/Tokens#46]
**Describe the bug**
>Cannot start server on latest paper version.

**Plugin version:** 3.9.6 - Latest release

**To Reproduce**

Start a server with Tokens and PaperSpigot 1.16.1 u will see an startup error

**Error message**
>If you have an error message copy and paste it on [this site](https://hastebin.com/), save it, then link us to it.
https://hasteb.in/aranejuv.sql

**Expected behavior**
> A clean startup, first time using this plugin.

**Screenshots**
>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/55764934/89755205-3496a100-daa4-11ea-9974-5c26077dd729.png)

**Comment by TheCoolestPaul** [comment]
It appears I've made this last update ignoring the fact that not everyone will have ShopGUI+!

For now you can just download the last version, I will drop an updated patching this in an hour or so.

**Comment by TheCoolestPaul** [comment]
Fixed with #48

**Comment by teszeo** [comment]
Thanks!
