### ISSUE TITLE
Add a option in config that can disable Auto-Update checks

### ISSUE THREAD

**Issue by Sapherises** [TheCoolestPaul/Tokens#52]
**Plugin name:** (Plugin's Name)
> Change to the plugin's name

**Plugin version:** (Version number OR LATEST)
> Change to LATEST or the plugin's version

**Spigot MC link:** [Link](https://www.spigotmc.org/)
> Change to the plugin's link

**How should it work?**
> What should a Token do? Give a level? Enhance a stat? Add an item? Let me know here!

**Comment by TheCoolestPaul** [comment]
I had planned to add this into the last update with SETTINGS on how often to check, but it seems I forgot to. I can add this in the next hotfix update.

**Comment by TheCoolestPaul** [comment]
If you would like to give it a test, I have a beta out for a new way of handling config files. It comes with the update-check options. 
It's available via CodeMC.io  [HERE](https://ci.codemc.io/job/TheCoolestPaul/job/Tokens/21/)
