### ISSUE TITLE
Confusing output /redeem

### ISSUE THREAD

**Issue by jordi00113** [TheCoolestPaul/Tokens#53]
**Describe the bug**
> First time using the plugin, I wanted to test the redeem command. When running /redeem it gives `Command usage: /redeem < key >`. As a server administrator, you'll immediately think for typing /redeem TestKey123 or another key. After a couple of minutes I discovered /redeem key outputs `Command usage: /redeem key < key >` 
Suggestion: When running /redeem outputs immediately `Command usage: /redeem key < key >` OR `use /redeem <key>` without key arg.

**Plugin version:** Tokens-3.9.7
**To Reproduce**
Run the commands:
/redeem
/redeem key

**Comment by TheCoolestPaul** [comment]
Alright, I'll get right on reformatting the output for the /redeem key command.

**Comment by TheCoolestPaul** [comment]
I'll actually word a way around this. I'll put the keys under `/token key <key>` and leave the redeem command strictly for _using_ Tokens on things.

**Comment by TheCoolestPaul** [comment]
Fixed with #68
