### ISSUE TITLE
Add Suport for plugin RankUp

### ISSUE THREAD

**Issue by tibika10** [TheCoolestPaul/Tokens#54]
Plugin name: (RankUp)

Spigot MC link: [Link](https://www.spigotmc.org/resources/rankup.76964/)

Hello!
I would like to be able to add to the requirements of each rankUp, an x ​​number of tokens to move to the next rank!

**Comment by TheCoolestPaul** [comment]
This is a great request! The plugin already has a API that I can hook Tokens directly into. I'll be sure to add support for this plugin.

I'm putting [this](https://github.com/okx-code/Rankup3/wiki/Developers) here for future reference.
