### ISSUE TITLE
WildStacker Support 

### ISSUE THREAD

**Issue by SevenX159** [TheCoolestPaul/Tokens#55]
Adding the support for Wildstacker, because when you start a server with wildstacker it crash Token

**Comment by PiggiesGoSqueal** [comment]
Peculiar. I recommend providing additional details to help the developer:
latest.log:
/version:
plugin version:

**Comment by SevenX159** [comment]
honestly i totally forget about that plugin i got another one working, so i can't provide latest.log nor any plugin version

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> honestly i totally forget about that plugin i got another one working, so i can't provide latest.log nor any plugin version

Ah ok. Which plugin if you don't mind my asking?

**Comment by SevenX159** [comment]
OptEco 
https://www.spigotmc.org/resources/opteco-1-8-1-16-3-points-system-with-mysql-and-more.76179/
