### ISSUE TITLE
Can you add a formatted `%tokens_getTokens%` placeholder?

### ISSUE THREAD

**Issue by Justsean2** [TheCoolestPaul/Tokens#64]

**Comment by Justsean2** [comment]
I would also be nice to see the `/tokens` command reply with a formatted balance.

**Comment by TheCoolestPaul** [comment]
It appears that I did not update the documentation! There is _already_ a formatted placeholder for Tokens. It's `%tokens_getTokensFormatted%` And I will add an option to format the `/tokens` command in the config.

**Comment by Justsean2** [comment]
Perfect! Thank you!!

**Comment by Justsean2** [comment]
@TheCoolestPaul I tried adding that placeholder (%tokens_getTokensFormatted%) to my scoreboard and it doesn't load. Is that placeholder supported in placeholderAPI?

**Comment by TheCoolestPaul** [comment]
> 
> 
> @TheCoolestPaul I tried adding that placeholder (%tokens_getTokensFormatted%) to my scoreboard and it doesn't load. Is that placeholder supported in placeholderAPI?

That is rather strange. I will look into it on the coming update!

**Comment by TheCoolestPaul** [comment]
It's working fine in my testing servers.

**Comment by RexEtImperator** [comment]
> @TheCoolestPaul I tried adding that placeholder (%tokens_getTokensFormatted%) to my scoreboard and it doesn't load. Is that placeholder supported in placeholderAPI?

I have same error
