### ISSUE TITLE
Redeem Command

### ISSUE THREAD

**Issue by JustTylerInit** [TheCoolestPaul/Tokens#65]
Hi, Paul.

I Cannot find a way to translate the tokens your plugin adds into MCMMO stats. I have used /redeem and worked out how to place in keys, though once I have created a Token balance I'm lost from there. The wiki also feels very niche and doesn't describe how to use the commands very well.

**Plugin version:** Most Recent.

1. I use command /Redeem Key TestKey123
2. I receive 10 tokens.
3.  I cannot find any command to further explore this plugin.

**Comment by TheCoolestPaul** [comment]
Hi JustTylerInit,

Firstly, I'd like to personally thank you for your feedback, it really helps me both learn and improve.

Secondly, I have made another issue #43 on this topic. I have a been ignoring it for some time in favor of coding the plugin. Once I release this next coming update I will start working on properly and thoroughly documenting this plugin.

Thank you again,
Paul

**Comment by TheCoolestPaul** [comment]
I have added a wiki page for redeeming Tokens. You can find it [HERE](https://github.com/TheCoolestPaul/Tokens/wiki/Redeem-Command). Let me know if there is anything you think I should add, or if you have any questions!
