### ISSUE TITLE
Tokens going in negative numbers

### ISSUE THREAD

**Issue by ThatOverPowered** [TheCoolestPaul/Tokens#79]
**Describe the bug**

Im using a plugin called "CommandPanels" basically a GUI maker, same thing as ChestCommand but better.
The thing is im making a shop using Tokens, and when removing the tokens from the player with /tokes remove the tokens are going to the infitinte in negative numbers, wich is letting the players buy unlimited things still not having tokens to do so.

**Plugin version:** 4.3.4

**To Reproduce**
Set your self on 0 tokens
Go to the console and remove your self some tokens.

**Error message**
No errors or warns on the console

**Expected behavior**
Tokens should have a minimun amount like 0, or an option to configure this. Like essentialsx have.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/50776804/126880311-08776303-065a-435c-9195-da95e81473b5.png)

**Additional context**
Server: PaperSpigot 1.17.1
Java 16
Windows 10 - 21H1

**Comment by TheCoolestPaul** [comment]
Expect this fixed in the next update here pretty soon.
