### ISSUE TITLE
Placeholders?

### ISSUE THREAD

**Issue by MrBobblyBooks** [TheCoolestPaul/Tokens#82]
I want to put the amount of tokens on my scoreboard? What are the placeholders for this plugin? like %tokens_amount%?

**Comment by TheCoolestPaul** [comment]
Tokens has built-in place holders ready for use.
You can use `%tokens_getTokens%` OR `%tokens_getTokensFormatted%`
To see the difference you can [checkout the wiki](https://tokens.thirdshift.net/supported-plugins/placeholderapi)
