### ISSUE TITLE
Tokens redeem key

### ISSUE THREAD

**Issue by MintSkye** [TheCoolestPaul/Tokens#9]
add a function into plugin which could create redeem key and player can use the keys to redeem some tokens.

**Comment by TheCoolestPaul** [comment]
Are you saying like a code admins/owners can create for players to turn into tokens?

**Comment by MintSkye** [comment]
Yes, it's a code for players to turn into tokens 😘

**Comment by TheCoolestPaul** [comment]
Okay I'll add that to my list!

**Comment by TheCoolestPaul** [comment]
Resolved with release #20
